CREATE TABLE IF NOT EXISTS projects (
  id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL, repo VARCHAR(300) UNIQUE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Healthy', uptime DOUBLE PRECISION NOT NULL DEFAULT 99.99
);
CREATE TABLE IF NOT EXISTS services (
  id SERIAL PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'Healthy',
  latency_ms DOUBLE PRECISION NOT NULL DEFAULT 120, uptime DOUBLE PRECISION NOT NULL DEFAULT 99.99
);
CREATE TABLE IF NOT EXISTS deployments (
  id SERIAL PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  sha VARCHAR(80) NOT NULL, message VARCHAR(300) NOT NULL, author VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Passed', created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS incidents (
  id SERIAL PRIMARY KEY, project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  title VARCHAR(300) NOT NULL, service VARCHAR(150) NOT NULL, severity VARCHAR(30) NOT NULL DEFAULT 'Warning',
  status VARCHAR(40) NOT NULL DEFAULT 'Investigating', confidence INTEGER NOT NULL DEFAULT 50,
  summary TEXT NOT NULL DEFAULT '', created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS incident_events (
  id SERIAL PRIMARY KEY, incident_id INTEGER NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  event_type VARCHAR(80) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS agent_runs (
  id SERIAL PRIMARY KEY, incident_id INTEGER NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  status VARCHAR(40) NOT NULL DEFAULT 'queued', confidence INTEGER NOT NULL DEFAULT 0,
  result TEXT NOT NULL DEFAULT '', created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
